use serde::Serialize;

#[derive(Debug, Clone, Serialize)]
pub struct RequestFilter {
    pub search: Option<String>,
    pub order_by: Option<String>,
    pub order: String,
    pub offset: Option<u64>,
    pub limit: Option<u64>,
    pub bookmark: bool,
    pub borrowing: bool,
    pub cas_number: Option<u64>,
    pub cas_number_cmr: bool,
    pub category: Option<u64>,
    pub custom_name_part_of: Option<String>,
    pub empirical_formula: Option<u64>,
    pub entity: Option<u64>,
    pub hazard_statements: Option<Vec<u64>>,
    pub history: bool,
    pub storages: Option<Vec<u64>>,
    pub name: Option<u64>,
    pub permission: String,
    pub precautionary_statements: Option<Vec<u64>>,
    pub producer: Option<u64>,
    pub producer_ref: Option<u64>,
    pub product: Option<u64>,
    pub product_specificity: Option<String>,
    pub show_bio: bool,
    pub show_chem: bool,
    pub show_consu: bool,
    pub signal_word: Option<u64>,
    pub storage: Option<u64>,
    pub storage_archive: bool,
    pub storage_barecode: Option<String>,
    pub storage_batch_number: Option<String>,
    pub storage_to_destroy: bool,
    pub store_location: Option<u64>,
    pub store_location_can_store: bool,
    pub supplier: Option<u64>,
    pub symbols: Option<Vec<u64>>,
    pub tags: Option<Vec<u64>>,
    pub unit_type: Option<String>,
}

impl Default for RequestFilter {
    fn default() -> RequestFilter {
        RequestFilter {
            search: None,
            order_by: None,
            order: String::from("asc"),
            offset: None,
            limit: None,
            bookmark: false,
            borrowing: false,
            cas_number: None,
            cas_number_cmr: false,
            category: None,
            custom_name_part_of: None,
            empirical_formula: None,
            entity: None,
            hazard_statements: None,
            history: false,
            storages: None,
            name: None,
            permission: String::from("r"),
            precautionary_statements: None,
            producer: None,
            producer_ref: None,
            product: None,
            product_specificity: None,
            show_bio: false,
            show_chem: false,
            show_consu: false,
            signal_word: None,
            storage: None,
            storage_archive: false,
            storage_barecode: None,
            storage_batch_number: None,
            storage_to_destroy: false,
            store_location: None,
            store_location_can_store: false,
            supplier: None,
            symbols: None,
            tags: None,
            unit_type: None,
        }
    }
}
